version: '3'
volumes:
  data-redis: {}
  data-mongo: {}
  data-mainapp: {}
services:
  mongo:
    restart: always
    image: mongo:3.4
    volumes:
      - data-mongo:/data/db
    expose:
      - "27017"
  redis:
    restart: always
    command: redis-server --appendonly yes
    image: redis:3.2
    expose:
        - "6379"
    volumes:
        - data-redis:/data
  integram:
    image: integram/integram:latest
    restart: always
    volumes:
      - data-mainapp:/app/.conf
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - ${INTEGRAM_PORT}:${INTEGRAM_PORT}
    environment:
      - TZ=UTC
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-main
      - INTEGRAM_CONFIG_DIR=/app/.conf
      ## required ENV vars
      - INTEGRAM_PORT
      - INTEGRAM_BASE_URL
  trello:
    image: integram/trello:latest
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - integram
    environment:
      - TZ=UTC
      - INTEGRAM_PORT=7000
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-service

      ## required ENV vars
      - INTEGRAM_BASE_URL
      - TRELLO_BOT_TOKEN
      - TRELLO_OAUTH_ID
      - TRELLO_OAUTH_SECRET
  gitlab:
    image: integram/gitlab
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - integram
    environment:
      - TZ=UTC
      - INTEGRAM_PORT=7000
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-service

      ## required ENV vars
      - INTEGRAM_BASE_URL
      - GITLAB_BOT_TOKEN
      - GITLAB_OAUTH_ID
      - GITLAB_OAUTH_SECRET
      - GITLAB_API_URL
# example - GITLAB_API_URL=http://localhost/api/v3/
  bitbucket:
    image: integram/bitbucket
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - integram
    environment:
      - TZ=UTC
      - INTEGRAM_PORT=7000
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-service

      ## required ENV vars
      - INTEGRAM_BASE_URL
      - BITBUCKET_BOT_TOKEN
      - BITBUCKET_OAUTH_ID
      - BITBUCKET_OAUTH_SECRET
  webhook:
    image: integram/webhook
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - integram
    environment:
      - TZ=UTC
      - INTEGRAM_PORT=7000
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-service

      ## required ENV vars
      - INTEGRAM_BASE_URL
      - WEBHOOK_BOT_TOKEN
